_default:
    @just --list

# Run ruff check with autofix
fix:
    uv run ruff check . --fix

# Run ruff check (no fix)
check:
    uv run ruff check .

# Run ruff format
fmt:
    uv run ruff format .

# Run pyright
type:
    uv run pyright .

# Run pre-commit hooks manually on all files
pre-commit:
    uv run pre-commit run --all-files

# Run unit tests
test:
    uv run pytest --quiet tests/

# Run ruff check, ruff format, pyright and unit tests
lint: fix fmt type test

# Check ruff lint, pyright and unit tests
check-all: check type test

# Watch Python files and run ruff and pyright on changes
watch:
    watchexec --exts=py --clear --restart "just check-all"
